libfreerdp-core: fixed transport
Commit 75a1b832fcc2379e3e21b237883346237f21773f introduced an
error: If transport_read_nonblocking returns 0 we may not return
without checking if the ReceiveBuffer is empty.