shadow: Fix typo with rdpSettings data type
This commit fixes the following compiler error.

FreeRDP/server/shadow/Win/win_wds.c:767:9: error: unknown type name 'rdpSetting';
did you mean 'rdpSettings'?
  767 |         rdpSetting* settings = subsystem->shw->settings;
      |         ^~~~~~~~~~
      |         rdpSettings

The typo was introduced in 0980fc4fbae9f30246df5f9596c8c263ebf56492 commit.